name: donwload_models
env:
  HF_TOKEN: ${{secrets.HUGGINGFACE_TOKEN}}
  REPO_NAME: meta-llama
  MODEL_NAME: Llama-3.2-3B-Instruct
  DOCKER_IMAGE: nvcr.io/nvidia/tritonserver:24.12-vllm-python-py3

on:
  push:
    branches:
      - execute
jobs:
  Prepare_docker_image_for_triton_inference_vllm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: download_weights
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Display Python version
        # uses: actions/setup-python@v4
        # with:
        #   python-version: 3.11
        run: |
          python --version
      - name: Install dependencies
        # uses: actions/setup-python@v4
        # with:
        #   python-version: 3.11
        run: |
          python -m pip install huggingface_hub
      
      - name: Download model
        run: |
          python download.py
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Setup Dockerfile
        run: |
          python write_dockerfile.py

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}

      - name: To lower case
        run: |
          echo "MODEL_NAME_LOWER=$(echo '${{ env.MODEL_NAME }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      
      - name: List files
        run: ls -R

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.docker_username }}/${{ env.MODEL_NAME_LOWER }}:latest
          # build-args: |
          #   HF_TOKEN=${{secrets.HUGGINGFACE_TOKEN

      #   run: |
      #     docker build -t ${{secrets.docker_username}}/${{env.MODEL_NAME}}:latest . 
      # - 
          